all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: 'e4:b9:7a:ef:8a:7d', network_interface: eth1}
        metal1: {ansible_host: 192.168.1.111, mac: '00:4e:01:aa:d2:a1', network_interface: eth1}
    workers:
      hosts: