netboot_url: "https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/netboot.tar.gz"
netboot_checksum: "sha256:0bc611f00357e133943e6b8abc6f11a1720945b64d4b3d945d43c8f2e9b6baba"
timezone: "America/New_York"
locale: "en_US"
country: "US"
language: "en"
keymap: "us"
domain: "local.domain"
dnsmasq_interface: "enp6s0"
mirror_country: "United States"
mirror_hostname: "http.us.debian.org"