home-assistant:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - &host hass.aharabedian.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
      - secretName: home-assistant-tls-certificate
        hosts:
          - *host
  persistence:
    enabled: true
    size: 10Gi
  garbageCollect:
    enabled: true
  metrics:
    enabled: true
  addons:
    codeserver:
      enabled: true
      args:
        - --auth
        - none
        - --user-data-dir
        - /data/config/.vscode
      volumeMounts:
      - name: config
        mountPath: /data/config