home-assistant:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host hass.aharabedian.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: home-assistant-tls
        hosts:
          - *host
  persistence:
    enabled: true
    size: 10Gi
  # addons:
  #   codeserver:
  #     enabled: true
  #     args:
  #       - --auth
  #       - none
  #       - --user-data-dir
  #       - /data/config/.vscode
  #     volumeMounts:
  #     - name: config
  #       mountPath: /data/config