- name: Send Wake-on-LAN packets
  community.general.wakeonlan:
    mac: "{{ mac }}"
  delegate_to: localhost

- name: Wait for machines to come online
  ansible.builtin.wait_for_connection:
    timeout: 600